"""FR-READ-03: the Claude Code PreToolUse hook blocks built-in reads of files that contain a secret.

Canary values are generated by bench/canary_repo.py; none is a real credential.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from bench.canary_repo import build
from Harpocrates import hooks


@pytest.fixture(scope="module")
def repo(tmp_path_factory: pytest.TempPathFactory) -> tuple[Path, list[dict]]:
    root = tmp_path_factory.mktemp("canary_repo")
    return root, build(root, seed=7)


def _run(event: dict, capsys: pytest.CaptureFixture) -> tuple[int, str]:
    code = hooks.decide(json.dumps(event))
    return code, capsys.readouterr().out


def _denied(out: str) -> bool:
    return bool(out) and json.loads(out)["hookSpecificOutput"]["permissionDecision"] == "deny"


def test_fr_read_03_hook_blocks_read_of_file_with_secret(repo, capsys) -> None:
    root, canaries = repo
    for rel in sorted({c["file"] for c in canaries}):
        code, out = _run({"tool_name": "Read", "cwd": str(root), "tool_input": {"file_path": rel}}, capsys)
        assert code == 0 and _denied(out), rel
        assert "safe_read" in out
        assert not any(c["value"][:12] in out for c in canaries), "the hook must never echo a secret"


def test_fr_read_03_hook_allows_clean_file(repo, capsys) -> None:
    root, _ = repo
    code, out = _run({"tool_name": "Read", "cwd": str(root), "tool_input": {"file_path": "README.md"}}, capsys)
    assert code == 0 and out == ""


def test_fr_read_03_hook_grep_content_mode(repo, capsys) -> None:
    root, _ = repo
    content = {"tool_name": "Grep", "cwd": str(root),
               "tool_input": {"pattern": "TOKEN", "path": str(root), "output_mode": "content"}}
    code, out = _run(content, capsys)
    assert code == 0 and _denied(out) and "safe_grep" in out
    names_only = {**content, "tool_input": {**content["tool_input"], "output_mode": "files_with_matches"}}
    assert _run(names_only, capsys) == (0, "")  # file names carry no secret
    clean = {**content, "tool_input": {**content["tool_input"], "pattern": "docker compose"}}
    assert _run(clean, capsys) == (0, "")


def test_fr_read_03_hook_bash_file_reads(repo, capsys) -> None:
    root, _ = repo
    def bash(cmd: str) -> dict:
        return {"tool_name": "Bash", "cwd": str(root), "tool_input": {"command": cmd}}
    for cmd in ("cat config/settings.py", "ls && head -n 5 src/client.js", "grep -n TOKEN < config/settings.py"):
        code, out = _run(bash(cmd), capsys)
        assert code == 0 and _denied(out), cmd
    for cmd in ("ls -la", "cat README.md", "git status"):
        assert _run(bash(cmd), capsys) == (0, ""), cmd


def test_fr_read_03_hook_fails_closed(repo, capsys, monkeypatch: pytest.MonkeyPatch) -> None:
    root, _ = repo
    assert hooks.decide("not json") == 2
    import Harpocrates.read as read

    monkeypatch.setattr(read.Redactor, "redact", lambda *_a: (_ for _ in ()).throw(RuntimeError("boom")))
    code = hooks.decide(json.dumps({"tool_name": "Read", "cwd": str(root), "tool_input": {"file_path": "README.md"}}))
    assert code == 2
    assert "boom" not in capsys.readouterr().out


def test_fr_read_03_hook_bash_codex_style_commands(repo, capsys) -> None:
    """Codex wraps commands in `zsh -lc` and loops over files; ripgrep searches the tree."""
    root, _ = repo
    def bash(cmd: str) -> dict:
        return {"tool_name": "Bash", "cwd": str(root), "tool_input": {"command": cmd}}
    blocked = ["/bin/zsh -lc 'for f in config/settings.py src/client.js; do nl -ba \"$f\"; done'",
               "bash -c \"sed -n '1,50p' src/client.js\"",
               "rg -n TOKEN", "grep -rn TOKEN .", "rg -e stripe config",
               "rg -n 'docker compose'"]  # shell searches never evaluate the pattern: whole scope counts
    for cmd in blocked:
        code, out = _run(bash(cmd), capsys)
        assert code == 0 and _denied(out), cmd
    allowed = ["rg --files", "rg -l TOKEN", "rg -n TOKEN README.md", "python -c 'print(1)'",
               "/bin/zsh -lc 'git status'", "pytest -q"]
    for cmd in allowed:
        assert _run(bash(cmd), capsys) == (0, ""), cmd


def _bash(root: Path, cmd: str) -> dict:
    return {"tool_name": "Bash", "cwd": str(root), "tool_input": {"command": cmd}}


def test_fr_read_03_hook_main_fails_closed_on_bad_stdin() -> None:
    import subprocess
    import sys

    proc = subprocess.run([sys.executable, "-m", "Harpocrates.hooks"], input=b"\xff\xfe", capture_output=True)
    assert proc.returncode == 2


def test_fr_read_03_hook_grep_semantics_fail_safe(repo, capsys, tmp_path: Path) -> None:
    root, _ = repo
    for extra in ({"pattern": "^AWS_SECRET"}, {"pattern": "aws_secret", "-i": True},
                  {"pattern": "[[:alpha:]]+"}, {"pattern": "(a+)+$"}):
        event = {"tool_name": "Grep", "cwd": str(root),
                 "tool_input": {"path": str(root), "output_mode": "content", **extra}}
        code, out = _run(event, capsys)
        assert code == 0 and _denied(out), extra
    big = tmp_path / "big.txt"
    big.write_text("x" * (11 * 1024 * 1024) + "\nAKIA" + "Q" * 16 + "\n")
    event = {"tool_name": "Grep", "cwd": str(tmp_path),
             "tool_input": {"pattern": "AKIA", "path": str(tmp_path), "output_mode": "content"}}
    code, out = _run(event, capsys)
    assert code == 0 and _denied(out)


def test_fr_read_03_hook_bash_review_cases(repo, capsys) -> None:
    root, _ = repo
    blocked = ["sudo bash -c 'cat .env'", "env bash -c 'cat .env'", "timeout 5 bash -c 'cat .env'",
               'echo "$(cat .env)"', "cat `echo .env`", "cd config && cat settings.py", "cat config/*",
               "cat ~/../../" + str(root).lstrip("/") + "/.env", "git show HEAD:config/settings.py",
               "dd if=.env", "cp .env /dev/stdout", "xargs -a .env echo", "rg -m 7 TOKEN .",
               "rg -t py TOKEN .", "rg -g '*.py' TOKEN"]
    for cmd in blocked:
        code, out = _run(_bash(root, cmd), capsys)
        assert code == 0 and _denied(out), cmd
    for cmd in ("cd config && ls", "git status", "rg -l TOKEN"):
        assert _run(_bash(root, cmd), capsys) == (0, ""), cmd


def test_fr_read_03_hook_environment(repo, capsys, monkeypatch: pytest.MonkeyPatch) -> None:
    root, canaries = repo
    token = next(c["value"] for c in canaries if c["kind"] == "github_token")
    monkeypatch.setenv("GITHUB_TOKEN", token)
    for cmd in ("env", "printenv", "echo $GITHUB_TOKEN", "echo ${GITHUB_TOKEN}", "cat /proc/self/environ"):
        code, out = _run(_bash(root, cmd), capsys)
        assert code == 0 and _denied(out) and token not in out, cmd
    assert _run(_bash(root, "echo $HOME"), capsys) == (0, "")


def test_fr_read_03_hook_match_timeout_counts_as_match(repo, capsys, monkeypatch: pytest.MonkeyPatch) -> None:
    """A pattern that stalls the matcher must not stall the hook into its own timeout (= allow)."""
    import subprocess

    root, _ = repo
    def stall(*_a, **kw):
        raise subprocess.TimeoutExpired(cmd="matcher", timeout=kw.get("timeout", 0))
    monkeypatch.setattr(hooks.subprocess, "run", stall)
    event = {"tool_name": "Grep", "cwd": str(root),
             "tool_input": {"pattern": "docker compose", "path": str(root), "output_mode": "content"}}
    code, out = _run(event, capsys)
    assert code == 0 and _denied(out)


def test_fr_read_03_hook_rereview_cases(repo, capsys, monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    root, canaries = repo
    blocked = ["rg --regexp=AWS_SECRET .env", "grep -eAWS_SECRET .env", "rg -nA 3 AWS_SECRET .env",
               "rg -v zzzz .env", "rg --passthru zzzz .env", "grep -E -v zzzz .env", "bash -x -c 'cat .env'",
               "bash --noprofile -c 'cat .env'", "eval 'cat .env'", "git grep AWS HEAD", "git blame .env"]
    for cmd in blocked:
        code, out = _run(_bash(root, cmd), capsys)
        assert code == 0 and _denied(out), cmd
    token = next(c["value"] for c in canaries if c["kind"] == "github_token")
    monkeypatch.setenv("GITHUB_TOKEN", token)
    for cmd in ('echo "$(printenv)"', "bash -c 'echo hi; env'"):
        code, out = _run(_bash(root, cmd), capsys)
        assert code == 0 and _denied(out) and token not in out, cmd
    assert _run(_bash(root, "git config set user.name x"), capsys) == (0, "")
    odd = tmp_path / "a\nb.txt"
    odd.write_text("AWS_ACCESS_KEY_ID=AKIA" + "QZ7XK2PLM9RT4VWB" + "\n")
    event = {"tool_name": "Grep", "cwd": str(tmp_path),
             "tool_input": {"pattern": "AWS", "path": str(tmp_path), "output_mode": "content"}}
    code, out = _run(event, capsys)
    assert code == 0 and _denied(out)
